server:
  address: 0.0.0.0
  port : 8081
  display-name: Help Desk Service
  context-path: /helpdesk
  connection-timeout: 20000

mongo:
  port: 27017
  database: helpdesk
  socketTimeout: 10000
  connectTimeout: 5000
  waitTimeout: 10000
  readPreference: nearest
  writeConcern: majority
  ignoreSSL: false

app-authentication:
  enabled: true
  pod:
    host: ${pod.host}
    port: ${pod.port:443}
  session_auth:
    host: ${session_auth.host}
    port: ${session_auth.port:443}
  filter:
    enabled: true
    url-patterns:
      - "/v1/*"
    excluded-paths:
      - "/v1/application/authenticate"
      - "/v1/application/tokens/validate"
      - "/v1/application/jwt/validate"
  api:
    enabled: true
    base-path: "/v1/application"
