# For debugging purposes, uncomment following lines
# logging:
#   level:
#     org.symphonyoss: DEBUG

server:
  address: 0.0.0.0
  port: 8100
  display-name: Help Desk Renderer
  context-path: /helpdesk-renderer
  connection-timeout: 20000

spring:
  mvc:
    dispatch-options-request: true
    media-types:
      json: application/json
      xml: application/xml
      csv: text/csv
      plain: text/plain
      x-www-form-urlencoded: application/x-www-form-urlencoded
      form-data: multipart/form-data
    servlet:
      load-on-startup: 1